#!/usr/bin/env python3
"""order_store_xlsx.py — the ACTUAL live/paper trades (order_store) into the SAME
cross-check workbook the backtest exporter emits, so you can eyeball what a strategy
REALLY did (e.g. the webhook incident) AND upload it to /lab/upload for the full
dashboard.

    python order_store_xlsx.py <strategy[,strategy...]> <from> <to> [out.xlsx]
    python order_store_xlsx.py arschain_MAIN 2026-07-01 2026-07-18

Reads order_store (LIVE DB — VPS only) -> maps each completed trade to the
Trades_BS schema -> recomputes the summary from those trades (self-consistency
cross-check) -> reuses xlsx_export's sheet writers. NOT a backtest: no what-if
path for sells, no backtest-claim; the Claude_Summary here == the live P&L summary.

Read-only: touches no order/risk/live path, only reads the trade DB.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
for p in (ROOT, HERE):
    if p not in sys.path:
        sys.path.insert(0, p)
import _paths  # noqa: F401
import openpyxl
from openpyxl.styles import Font

import order_store
import xlsx_export as XE
import xlsx_import as XI

_STRIKE_RE = re.compile(r"(\d+(?:\.\d+)?)\s*(CE|PE)\s*$", re.I)


def _parse_sym(sym):
    """(strike, opt_type) from a trad_sym like 'NIFTY-17Jul2026-24000-CE'."""
    sym = str(sym or "")
    m = _STRIKE_RE.search(sym.replace(" ", ""))
    if m:
        try:
            return float(m.group(1)), m.group(2).upper()
        except ValueError:
            pass
    return None, ("CE" if sym.upper().endswith("CE") else ("PE" if sym.upper().endswith("PE") else ""))


def _to_all_trades(details):
    """order_store `details` -> results.js all_trades-shaped list."""
    out = []
    for t in details:
        if t.get("pnl") is None:
            continue
        strike, opt = _parse_sym(t.get("sym") or t.get("symbol"))
        # entry field = BUY/SELL of the OPTION: bought option = long-premium, sold = short
        side = "short" if str(t.get("entry", "")).upper() == "SELL" else "long"
        ed = (str(t.get("entry_date", "")) + " " + str(t.get("entry_time", ""))).strip()
        xd = (str(t.get("exit_date") or t.get("entry_date", "")) + " "
              + str(t.get("exit_time") or "")).strip()
        out.append({
            "side": side, "opt_type": opt, "strike": strike,
            "entry_dt": ed, "exit_dt": xd,
            "entry_prem": t.get("entry_price"), "exit_prem": t.get("exit_price"),
            "points": None, "qty": t.get("qty"),
            "entry_spot": None, "exit_spot": None,
            "gross": None, "fee": None, "pnl": t.get("pnl"),
            "bars": 0, "reason": t.get("exit_reason") or "",
            # live-only extras (kept for the eyeball sheet, ignored by the dashboard)
            "_mode": t.get("mode"), "_broker": t.get("broker"), "_tags": t.get("tags"),
        })
    return out


def _readme(wb, strat, d_from, d_to, n):
    ws = wb.active
    ws.title = "README"
    lines = [
        ("LIVE TRADES WORKBOOK  (order_store — NOT a backtest)", True),
        ("", 0),
        ("Strategy: {}   Window: {} -> {}   Trades: {}".format(strat, d_from, d_to, n), 0),
        ("", 0),
        ("Trades_BS      = jo strategy ne ASLI me kiya (live/paper fills). Yahi eyeball karo.", 0),
        ("Claude_Summary = inhi trades ka P&L summary (self-consistency cross-check).", 0),
        ("Flags          = 0-P&L / duplicate / no-move / missing-exit-reason anomaly.", 0),
        ("", 0),
        ("Ye /lab/upload pe daal ke poora dashboard bhi dekh sakte ho (equity/monthly/etc.).", 0),
        ("NOTE: ye backtest NAHI — no what-if path for sells, no validated Sharpe claim.", 0),
        ("Sharpe 'info (path-based)' hamesha aayega (calendar-day equity trades me nahi).", 0),
    ]
    for i, (txt, big) in enumerate(lines, 1):
        c = ws.cell(i, 1, txt)
        c.font = Font(bold=bool(big), size=13 if big else 10,
                      color="0969DA" if big else "24292F")
    ws.column_dimensions["A"].width = 96


def _meta_sheet(wb, strat, d_from, d_to, trades):
    ws = wb.create_sheet("Meta")
    modes = sorted({str(t.get("_mode")) for t in trades if t.get("_mode")})
    brokers = sorted({str(t.get("_broker")) for t in trades if t.get("_broker")})
    rows = [
        ("Field", "Value"),
        ("Source", "order_store (LIVE trades DB)"),
        ("Strategy", strat),
        ("Window", "{} -> {}".format(d_from, d_to)),
        ("Trades", len(trades)),
        ("Mode(s)", ", ".join(modes) or "-"),
        ("Broker(s)", ", ".join(brokers) or "-"),
        ("Instrument", "NIFTY 50 options"),
        ("Generated by", "order_store_xlsx.py (read-only)"),
    ]
    from openpyxl.styles import PatternFill
    HF = Font(bold=True, color="FFFFFF", size=10)
    HDR = PatternFill("solid", fgColor="1F6FEB")
    for r, row in enumerate(rows, 1):
        for cc, v in enumerate(row, 1):
            cell = ws.cell(r, cc, v)
            if r == 1:
                cell.font = HF; cell.fill = HDR
            elif cc == 1:
                cell.font = Font(bold=True)
    ws.column_dimensions["A"].width = 16
    ws.column_dimensions["B"].width = 60


def export_live(strategies, d_from, d_to, out_path=None):
    det = order_store.trades_for_range(d_from, d_to).get("details", [])
    want = {s.strip() for s in strategies}
    det = [t for t in det if str(t.get("strategy")) in want]
    trades = _to_all_trades(det)
    if not trades:
        print("  [none] no completed trades for", strategies, d_from, d_to)
        return None
    metrics = XI.recompute(trades)
    meta = {"lot_size": 75, "tf": "5m"}          # for the what-if lots calc (sells -> N/A)
    label = "+".join(strategies)

    wb = openpyxl.Workbook()
    _readme(wb, label, d_from, d_to, len(trades))
    _meta_sheet(wb, label, d_from, d_to, trades)
    XE._summary_sheet(wb, metrics)
    covered, n = XE._trades_bs(wb, trades, meta)
    XE._flags_sheet(wb, trades, covered, n)

    if not out_path:
        out_path = os.path.join(HERE, "runs", "_live",
                                "live_{}_{}_{}.xlsx".format(label.replace("+", "-"), d_from, d_to))
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
    wb.save(out_path)
    net = sum(t["pnl"] for t in trades if t["pnl"] is not None)
    print("  [ok] {}  {} trades  net Rs{:,.0f}  ->  {}".format(label, n, net, out_path))
    return out_path


if __name__ == "__main__":
    a = sys.argv[1:]
    if len(a) < 3:
        print(__doc__); sys.exit(0)
    strategies = a[0].split(",")
    out = a[3] if len(a) > 3 else None
    export_live(strategies, a[1], a[2], out)
