#!/usr/bin/env python3
"""xlsx_export.py — turn a backtest run's results.js into ONE cross-check workbook.

    python xlsx_export.py <slug> [<slug> ...]     # named runs
    python xlsx_export.py --all                    # every run in runs/index.json

Writes runs/<slug>/<slug>.xlsx with sheets:
    README            plain-Hinglish guide
    Meta              strategy / instrument / params / window
    Claude_Summary    the metrics Claude claims  (3-way cross-check anchor)
    Trades_BS         GROUND TRUTH (Black-Scholes pass) + evolving what-if columns
    Trades_RMS        pass 2 spot P&L (daily caps)          [if present]
    Trades_Instrument pass 1 raw spot P&L                    [if present]
    Flags             auto-anomaly eyeball sheet

The lab (`/lab/upload`) re-reads this file, recomputes the metrics from Trades_BS
with the canonical engine, and flags any drift vs Claude_Summary.

Display-only: reads results.js, writes an xlsx. Touches no live/order/risk path.
"""
import os
import sys
import json
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import whatif_engine as W

RUNS = os.path.join(HERE, "runs")

HDR = PatternFill("solid", fgColor="1F6FEB")
HDR_WI = PatternFill("solid", fgColor="6E40C9")
HF = Font(bold=True, color="FFFFFF", size=10)
GREEN = Font(color="1A7F37"); RED = Font(color="CF222E"); BOLD = Font(bold=True)
CEN = Alignment(horizontal="center")


def _load(slug):
    p = os.path.join(RUNS, slug, "results.js")
    raw = open(p, encoding="utf-8").read().strip()
    raw = raw[raw.index("{"):]
    if raw.endswith(";"):
        raw = raw[:-1]
    return json.loads(raw)


def _combo(R, pass_):
    return R["combos"].get(pass_ + "|full") or (R["combos"].get("full") if pass_ == "bs" else None)


def _hdr(ws, wi_from=None):
    for c in ws[1]:
        c.font = HF
        c.fill = HDR_WI if (wi_from and c.column >= wi_from) else HDR
        c.alignment = CEN


def _readme(wb):
    ws = wb.active; ws.title = "README"
    L = [
        ("BACKTEST CROSS-CHECK WORKBOOK", True),
        ("", 0),
        ("3 aankhon ka cross-check — ek hi trade-list pe:", 0),
        ("  1) Trades_BS       = GROUND TRUTH. Har trade ek row. Tu yahi eyeball karega.", 0),
        ("  2) Claude_Summary  = jo numbers MAIN claim karta hun.", 0),
        ("  3) Lab (upload)    = ye trades padhke KHUD dobara ginega, phir #2 se compare.", 0),
        ("     Mismatch = red flag (CAGR/TRAP-127 wali cheez apne aap pakdi jayegi).", 0),
        ("", 0),
        ("Trades_BS ke what-if columns EVOLVING hain (Fixed T/SL, RR 1:1/1:2/1:3, Aggr Trail).", 0),
        ("Naya what-if chahiye -> whatif_engine.COLUMNS me add, wo apne aap sheet me aa jayega.", 0),
        ("", 0),
        ("3 passes = 3 sheets: Trades_BS (deployable, option premium) / _RMS / _Instrument (spot).", 0),
        ("What-if sirf BS pass pe (option-premium based). '-' = single-leg nahi (structure) ya data-gap.", 0),
    ]
    for i, (t, big) in enumerate(L, 1):
        c = ws.cell(i, 1, t)
        c.font = Font(bold=bool(big), size=13 if big else 10,
                      color="0969DA" if big else "24292F")
    ws.column_dimensions["A"].width = 98


def _meta_sheet(wb, R, bs_combo):
    m = R["meta"]; ws = wb.create_sheet("Meta")
    rows = [
        ("Field", "Value"),
        ("Strategy", m.get("design")),
        ("Slug", m.get("slug")),
        ("Instrument", m.get("instrument")),
        ("Timeframe", m.get("tf")),
        ("Lot size", m.get("lot_size")),
        ("Lots", m.get("lots")),
        ("Window", " -> ".join(m.get("window", []))),
        ("Trading days", m.get("days")),
        ("Passes", ", ".join(m.get("passes", ["bs"]))),
        ("Params (dna)", json.dumps(bs_combo.get("dna", {}))),
        ("Generated by", "xlsx_export.py (display-only, from results.js)"),
    ]
    for r, row in enumerate(rows, 1):
        for cc, v in enumerate(row, 1):
            cell = ws.cell(r, cc, v)
            if r == 1: cell.font = HF; cell.fill = HDR
            elif cc == 1: cell.font = BOLD
    ws.column_dimensions["A"].width = 16; ws.column_dimensions["B"].width = 72


def _summary_sheet(wb, metrics):
    ws = wb.create_sheet("Claude_Summary")
    def g(k): return metrics.get(k, "-")
    rows = [
        ("Metric", "Claude claims", "note"),
        ("Trades", g("trades"), ""),
        ("Net %  (fixed-1-lot, NOT CAGR)", g("net_pct"), "TRAP-127: lab cross-checks this"),
        ("Net Rs", g("net_abs"), ""),
        ("Sharpe", g("sharpe"), ""),
        ("Sortino", g("sortino"), ""),
        ("Profit Factor", g("profit_factor"), ""),
        ("Win rate %", g("win_rate"), ""),
        ("Max DD %", g("maxdd"), ""),
        ("Expectancy Rs", g("expectancy"), ""),
        ("Avg win | Avg loss", "{} | {}".format(g("avg_win"), g("avg_loss")), ""),
        ("Total fees Rs", g("fees"), ""),
    ]
    for r, row in enumerate(rows, 1):
        for cc, v in enumerate(row, 1):
            cell = ws.cell(r, cc, v)
            if r == 1: cell.font = HF; cell.fill = HDR
            elif cc == 1: cell.font = BOLD
    ws.column_dimensions["A"].width = 32
    ws.column_dimensions["B"].width = 18
    ws.column_dimensions["C"].width = 30


def _trades_bs(wb, trades, meta):
    ws = wb.create_sheet("Trades_BS")
    lot = int(meta.get("lot_size", 65) or 65)
    base = ["#", "Date", "Side", "Opt", "Strike", "In", "Out", "Bars",
            "Entry Prem", "Exit Prem", "Prem Pts", "Qty", "Index Pts",
            "Entry Spot", "Exit Spot",
            "Gross Rs", "Fee Rs", "Net Rs", "Exit Reason"]
    wi_labels = [lbl for _, lbl in W.COLUMNS]
    header = base + wi_labels + ["Flag"]
    ws.append(header)
    wi_from = len(base) + 1

    wi = W.compute(trades, meta)
    for i, (t, w) in enumerate(zip(trades, wi), 1):
        net = t.get("pnl")
        ep, xp = t.get("entry_prem"), t.get("exit_prem")
        flag = "OK"
        if net in (None, 0): flag = "ZERO-PNL?"
        elif ep is not None and ep == xp: flag = "NO-MOVE?"
        row = [
            i, str(t.get("entry_dt", ""))[:10], str(t.get("side", "")).upper(),
            t.get("opt_type", ""), t.get("strike", ""),
            str(t.get("entry_dt", ""))[11:16], str(t.get("exit_dt", ""))[11:16],
            t.get("bars", ""), ep, xp,
            round((xp or 0) - (ep or 0), 2), t.get("qty", ""), t.get("points", ""),
            t.get("entry_spot", ""), t.get("exit_spot", ""),
            round(t.get("gross", 0) or 0, 1), round(t.get("fee", 0) or 0, 1),
            round(net, 1) if net is not None else "", t.get("reason", ""),
        ]
        for key, _ in W.COLUMNS:
            v = w.get(key)
            row.append(v if v is not None else "-")
        row.append(flag)
        ws.append(row)

    _hdr(ws, wi_from=wi_from)
    net_col = base.index("Net Rs") + 1
    flag_col = len(header)
    for r in range(2, ws.max_row + 1):
        v = ws.cell(r, net_col).value
        if isinstance(v, (int, float)):
            ws.cell(r, net_col).font = GREEN if v >= 0 else RED
        fl = ws.cell(r, flag_col).value
        if fl and fl != "OK":
            ws.cell(r, flag_col).font = Font(color="CF222E", bold=True)
    widths = ([4, 11, 6, 5, 7, 6, 6, 5, 10, 10, 9, 6, 9, 10, 10, 9, 8, 9, 15]
              + [15] * len(wi_labels) + [11])
    for i, wd in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = wd
    ws.freeze_panes = "A2"
    covered = sum(1 for x in wi if x["covered"])
    return covered, len(trades)


def _trades_spot(wb, name, trades):
    if not trades:
        return
    ws = wb.create_sheet(name)
    header = ["#", "Date", "Side", "In", "Out", "Bars", "Entry", "Exit",
              "Points", "Qty", "Gross Rs", "Fee Rs", "Net Rs", "Exit Reason"]
    ws.append(header)
    for i, t in enumerate(trades, 1):
        net = t.get("pnl")
        ws.append([
            i, str(t.get("entry_dt", ""))[:10], str(t.get("side", "")).upper(),
            str(t.get("entry_dt", ""))[11:16], str(t.get("exit_dt", ""))[11:16],
            t.get("bars", ""), t.get("entry_spot", t.get("entry", "")),
            t.get("exit_spot", t.get("exit", "")), t.get("points", ""),
            t.get("qty", ""), round(t.get("gross", 0) or 0, 1),
            round(t.get("fee", 0) or 0, 1), round(net, 1) if net is not None else "",
            t.get("reason", ""),
        ])
    _hdr(ws)
    nc = 13
    for r in range(2, ws.max_row + 1):
        v = ws.cell(r, nc).value
        if isinstance(v, (int, float)):
            ws.cell(r, nc).font = GREEN if v >= 0 else RED
    for i, wd in enumerate([4, 11, 6, 6, 6, 5, 9, 9, 8, 6, 9, 8, 9, 15], 1):
        ws.column_dimensions[get_column_letter(i)].width = wd
    ws.freeze_panes = "A2"


def _flags_sheet(wb, trades, covered, n_total):
    ws = wb.create_sheet("Flags")
    ws.append(["Check", "Count", "Meaning"])
    n_zero = sum(1 for t in trades if t.get("pnl") in (None, 0))
    seen = set(); n_dup = 0
    for t in trades:
        k = (t.get("entry_dt"), t.get("strike"), t.get("side"))
        if k in seen: n_dup += 1
        seen.add(k)
    n_same = sum(1 for t in trades if t.get("entry_prem") is not None
                 and t.get("entry_prem") == t.get("exit_prem"))
    rows = [
        ("Total trades", n_total, "kitni rows"),
        ("Zero / null P&L", n_zero, "phantom / Rs0-fill bug ka lakshan"),
        ("Duplicate (date+strike+side)", n_dup, "double-count ka lakshan"),
        ("Entry Prem == Exit Prem", n_same, "no-move / data gap"),
        ("What-if covered", "{}/{}".format(covered, n_total), "single-leg computed; baaki structure/gap"),
    ]
    for r, row in enumerate(rows, 2):
        for cc, v in enumerate(row, 1):
            ws.cell(r, cc, v)
    _hdr(ws)
    ws.column_dimensions["A"].width = 30
    ws.column_dimensions["B"].width = 12
    ws.column_dimensions["C"].width = 42


def export_run(slug):
    R = _load(slug)
    bs_combo = _combo(R, "bs")
    if not bs_combo:
        print("  [skip]", slug, "- no bs/full combo")
        return None
    trades = bs_combo["all_trades"]
    metrics = dict(bs_combo["metrics"])
    if "fees" not in metrics:
        metrics["fees"] = round(sum(t.get("fee", 0) or 0 for t in trades), 0)

    wb = openpyxl.Workbook()
    _readme(wb)
    _meta_sheet(wb, R, bs_combo)
    _summary_sheet(wb, metrics)
    covered, n = _trades_bs(wb, trades, R["meta"])
    rms = _combo(R, "rms"); inst = _combo(R, "instrument")
    _trades_spot(wb, "Trades_RMS", rms["all_trades"] if rms else None)
    _trades_spot(wb, "Trades_Instrument", inst["all_trades"] if inst else None)
    _flags_sheet(wb, trades, covered, n)

    out = os.path.join(RUNS, slug, slug + ".xlsx")
    wb.save(out)
    print("  [ok]  {}  ->  {}.xlsx  ({} trades, what-if {}/{})".format(
        slug, slug, n, covered, n))
    return out


def _all_slugs():
    idx = json.load(open(os.path.join(RUNS, "index.json"), encoding="utf-8"))
    return [r["slug"] for r in idx]


if __name__ == "__main__":
    args = sys.argv[1:]
    if not args:
        print(__doc__); sys.exit(0)
    slugs = _all_slugs() if args[0] == "--all" else args
    print("Exporting {} run(s)...".format(len(slugs)))
    for s in slugs:
        try:
            export_run(s)
        except Exception as e:
            print("  [ERR]", s, "-", e)
